declare module 'services';
declare module 'components';
declare module '__mocks__';
declare module '*.png';
declare module '*.jpg';
declare module '*.jpeg';
declare module '*.gif';
declare module '*.svg';
declare module '*.json';